package com.udacity.project4.utils

import java.util.concurrent.TimeUnit

const val SIGN_IN_RESULT_CODE = 1001
const val REQUEST_LOCATION_PERMISSION = 1
const val REQUEST_FOREGROUND_AND_BACKGROUND_PERMISSION_RESULT_CODE = 33
const val REQUEST_FOREGROUND_ONLY_PERMISSIONS_REQUEST_CODE = 34
const val REQUEST_TURN_DEVICE_LOCATION_ON = 29
const val TAG = "Project4"
const val LOCATION_PERMISSION_INDEX = 0
const val BACKGROUND_LOCATION_PERMISSION_INDEX = 1
const val ACTION_GEOFENCE_EVENT = "udacity.project4.action.ACTION_GEOFENCE_EVENT"
const val GEOFENCE_RADIUS_IN_METERS = 100f
val GEOFENCE_EXPIRATION_IN_MILLISECONDS: Long = TimeUnit.HOURS.toMillis(1)